# Generated by Django 4.1 on 2022-08-21 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=30, verbose_name='Название клуба: ')),
                ('club_img', models.ImageField(blank=True, null=True, upload_to='media/club/%y/%m/%d/', verbose_name='Загрузить логотип: ')),
            ],
            options={
                'verbose_name': 'Клуб',
                'verbose_name_plural': 'Клубы',
            },
        ),
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medal_name', models.CharField(max_length=15, verbose_name='Вид медали: ')),
            ],
            options={
                'verbose_name': 'Медаль',
                'verbose_name_plural': 'Медали',
            },
        ),
        migrations.CreateModel(
            name='Sportsman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sportsman_name', models.CharField(max_length=50, verbose_name='ФИО спортсмена: ')),
                ('sportsman_country', models.CharField(max_length=30, verbose_name='Страна')),
                ('sportsman_birthday', models.DateField(max_length=8, verbose_name='Дата рождения')),
                ('sportsman_biogrpahy', models.TextField(blank=True, null=True, verbose_name='Описание книги')),
                ('sportsman_img', models.ImageField(blank=True, null=True, upload_to='media/trener/%y/%m/%d/', verbose_name='Загрузить фото: ')),
            ],
            options={
                'verbose_name': 'Спортсмен',
                'verbose_name_plural': 'Спортсмены',
            },
        ),
        migrations.CreateModel(
            name='ViewOlimp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_olimp_name', models.CharField(max_length=50, verbose_name='Наименование олимпийских игр: ')),
            ],
            options={
                'verbose_name': 'Вид олимпийских игр',
                'verbose_name_plural': 'Вид олимпийских игр',
            },
        ),
        migrations.CreateModel(
            name='ViewSports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_sport_name', models.CharField(max_length=50, verbose_name='Наименование вида спорта: ')),
            ],
            options={
                'verbose_name': 'Вид спорта',
                'verbose_name_plural': 'Вид спорта',
            },
        ),
        migrations.CreateModel(
            name='Trener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trener_name', models.CharField(max_length=50, verbose_name='ФИО тренера: ')),
                ('trener_img', models.ImageField(blank=True, null=True, upload_to='media/trener/%y/%m/%d/', verbose_name='Загрузить фото: ')),
                ('club_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Club_Trener', to='olimp.club', verbose_name='club_id')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand_name', models.CharField(max_length=50, verbose_name='Заголовок стэнда: ')),
                ('stand_description', models.TextField(blank=True, null=True, verbose_name='Описание стэнда')),
                ('date_event', models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения олимпиады')),
                ('medal_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Medal_Stand', to='olimp.medal', verbose_name='medal_id')),
                ('sportsman_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sportsman_Stand', to='olimp.sportsman', verbose_name='sportsman_id')),
                ('view_olimp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ViewOlimp_Stand', to='olimp.viewolimp', verbose_name='view_olimp_id')),
            ],
            options={
                'verbose_name': 'Стенд',
                'verbose_name_plural': 'Стенды',
            },
        ),
        migrations.AddField(
            model_name='sportsman',
            name='trener_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Trener_Sportsman', to='olimp.trener', verbose_name='view_sports_id'),
        ),
        migrations.AddField(
            model_name='sportsman',
            name='view_sports_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ViewSports_Sportsman', to='olimp.viewsports', verbose_name='view_sports_id'),
        ),
    ]
