# Generated by Django 4.1 on 2022-08-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_is_visible',
            field=models.BooleanField(default=False, verbose_name='Удалить'),
        ),
        migrations.AddField(
            model_name='medal',
            name='medal_is_visible',
            field=models.BooleanField(default=False, verbose_name='Удалить'),
        ),
        migrations.AddField(
            model_name='sportsman',
            name='sportsman_is_visible',
            field=models.BooleanField(default=False, verbose_name='Удалить'),
        ),
        migrations.AddField(
            model_name='stand',
            name='stand_is_visible',
            field=models.BooleanField(default=False, verbose_name='Удалить'),
        ),
        migrations.AddField(
            model_name='trener',
            name='traner_is_visible',
            field=models.BooleanField(default=False, verbose_name='Удалить'),
        ),
        migrations.AddField(
            model_name='viewolimp',
            name='view_olimp_is_visble',
            field=models.BooleanField(default=False, verbose_name='Удалить'),
        ),
        migrations.AddField(
            model_name='viewsports',
            name='view_sports_is_visible',
            field=models.BooleanField(default=False, verbose_name='Удалить'),
        ),
    ]
