# Generated by Django 4.1 on 2022-08-21 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0002_club_club_is_visible_medal_medal_is_visible_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trener',
            options={'verbose_name': 'Тренер', 'verbose_name_plural': 'Тренера'},
        ),
        migrations.RenameField(
            model_name='trener',
            old_name='traner_is_visible',
            new_name='trener_is_visible',
        ),
    ]
