# Generated by Django 4.1 on 2022-08-21 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0004_alter_club_club_is_visible_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'КЛУБ', 'verbose_name_plural': 'КЛУБЫ'},
        ),
        migrations.AlterModelOptions(
            name='medal',
            options={'verbose_name': 'МЕДАЛЬ', 'verbose_name_plural': 'МЕДАЛИ'},
        ),
        migrations.AlterModelOptions(
            name='sportsman',
            options={'verbose_name': 'СПОРТСМЕН', 'verbose_name_plural': 'СПОРТСМЕНЫ'},
        ),
        migrations.AlterModelOptions(
            name='stand',
            options={'verbose_name': 'СТЕНД', 'verbose_name_plural': 'СТЕНДЫ'},
        ),
        migrations.AlterModelOptions(
            name='trener',
            options={'verbose_name': 'ТРЕНЕР', 'verbose_name_plural': 'ТРЕНЕРА'},
        ),
        migrations.AlterModelOptions(
            name='viewolimp',
            options={'verbose_name': 'ВИД ОЛИМПИЙСКИХ ИГР', 'verbose_name_plural': 'ВИД ОЛИМПИЙСКИХ ИГР'},
        ),
        migrations.AlterModelOptions(
            name='viewsports',
            options={'verbose_name': 'ВИД СПОРТА', 'verbose_name_plural': 'ВИД СПОРТА'},
        ),
    ]
