# Generated by Django 4.1 on 2022-08-21 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0006_alter_club_club_is_visible_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stand',
            options={'verbose_name': 'СТЕНД', 'verbose_name_plural': 'СТЕНД'},
        ),
    ]
