# Generated by Django 4.1 on 2022-08-21 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0007_alter_stand_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trener',
            options={'verbose_name': 'ТРЕНЕРА', 'verbose_name_plural': 'ТРЕНЕРЫ'},
        ),
    ]
