# Generated by Django 4.1 on 2022-08-21 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0009_alter_club_club_is_visible_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewolimp',
            old_name='view_olimp_is_visble',
            new_name='view_olimp_is_visible',
        ),
    ]
