# Generated by Django 4.1 on 2022-08-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0011_alter_club_club_is_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medal',
            name='medal_name',
            field=models.CharField(max_length=20, verbose_name='Вид медали: '),
        ),
    ]
