# Generated by Django 4.1 on 2022-08-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0012_alter_medal_medal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsman',
            name='sportsman_biogrpahy',
            field=models.TextField(blank=True, null=True, verbose_name='Биография>: '),
        ),
    ]
