# Generated by Django 4.1 on 2022-08-21 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0013_alter_sportsman_sportsman_biogrpahy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportsman',
            options={'verbose_name': 'СПОРТСМЕНА', 'verbose_name_plural': 'СПОРТСМЕНЫ'},
        ),
    ]
