# Generated by Django 4.1 on 2022-08-21 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0014_alter_sportsman_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsman',
            name='trener_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Trener_Sportsman', to='olimp.trener', verbose_name='trener_id: '),
        ),
    ]
