# Generated by Django 4.1 on 2022-08-21 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0016_alter_viewolimp_options_alter_club_club_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_img',
            field=models.ImageField(upload_to='media/club/%y/%m/%d/', verbose_name='Загрузить логотип'),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_is_visible',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Скрытая запись'),
        ),
        migrations.AlterField(
            model_name='medal',
            name='medal_is_visible',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Скрытая запись'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='sportsman_img',
            field=models.ImageField(upload_to='media/trener/%y/%m/%d/', verbose_name='Загрузить фото'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='sportsman_is_visible',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Скрытая запись'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='trener_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Trener_Sportsman', to='olimp.trener', verbose_name='trener_id'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='view_sports_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ViewSports_Sportsman', to='olimp.viewsports', verbose_name='view_sports_id'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='date_event',
            field=models.DateTimeField(null=True, verbose_name='Дата проведения олимпиады'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='medal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Medal_Stand', to='olimp.medal', verbose_name='medal_id'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='sportsman_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sportsman_Stand', to='olimp.sportsman', verbose_name='sportsman_id'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='stand_is_visible',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Скрытая запись'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='view_olimp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ViewOlimp_Stand', to='olimp.viewolimp', verbose_name='view_olimp_id'),
        ),
        migrations.AlterField(
            model_name='trener',
            name='club_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Club_Trener', to='olimp.club', verbose_name='club_id'),
        ),
        migrations.AlterField(
            model_name='trener',
            name='trener_img',
            field=models.ImageField(upload_to='media/trener/%y/%m/%d/', verbose_name='Загрузить фото'),
        ),
        migrations.AlterField(
            model_name='trener',
            name='trener_is_visible',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Скрытая запись'),
        ),
        migrations.AlterField(
            model_name='viewolimp',
            name='view_olimp_is_visible',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Скрытая запись'),
        ),
        migrations.AlterField(
            model_name='viewsports',
            name='view_sports_is_visible',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Скрытая запись'),
        ),
    ]
