# Generated by Django 4.1 on 2022-08-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0017_alter_club_club_img_alter_club_club_is_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='stand_description',
            field=models.TextField(verbose_name='Описание стэнда'),
        ),
    ]
