# Generated by Django 4.1 on 2022-08-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0018_alter_stand_stand_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='date_event',
            field=models.DateField(null=True, verbose_name='Дата проведения олимпиады'),
        ),
    ]
