# Generated by Django 4.1 on 2022-08-21 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0020_alter_stand_date_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsman',
            name='trener_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Trener_Sportsman', to='olimp.trener', verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='view_sports_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ViewSports_Sportsman', to='olimp.viewsports', verbose_name='Вид спорта'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='medal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Medal_Stand', to='olimp.medal', verbose_name='Медаль'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='sportsman_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sportsman_Stand', to='olimp.sportsman', verbose_name='Спортсмен'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='view_olimp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ViewOlimp_Stand', to='olimp.viewolimp', verbose_name='Вид олимпийских игр'),
        ),
        migrations.AlterField(
            model_name='trener',
            name='club_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Club_Trener', to='olimp.club', verbose_name='Клуб'),
        ),
    ]
