# Generated by Django 4.1 on 2022-08-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0021_alter_sportsman_trener_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsman',
            name='sportsman_img',
            field=models.ImageField(upload_to='media/sportsman/%y/%m/%d/', verbose_name='Загрузить фото'),
        ),
    ]
