# Generated by Django 4.1 on 2022-08-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0022_alter_sportsman_sportsman_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='stand_description',
            field=models.TextField(verbose_name='Описание стенда'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='stand_name',
            field=models.CharField(max_length=50, verbose_name='Заголовок стенда'),
        ),
    ]
