# Generated by Django 4.1 on 2022-08-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0023_alter_stand_stand_description_alter_stand_stand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='stand_description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='stand_name',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
    ]
