# Generated by Django 4.1 on 2022-08-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0024_alter_stand_stand_description_alter_stand_stand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='stand_description',
            field=models.TextField(max_length=100, verbose_name='Описание записи'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='stand_name',
            field=models.CharField(max_length=20, verbose_name='Заголовок записи'),
        ),
    ]
