# Generated by Django 4.1 on 2022-08-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0025_alter_stand_stand_description_alter_stand_stand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='stand_name',
            field=models.CharField(max_length=40, verbose_name='Заголовок записи'),
        ),
    ]
