# Generated by Django 4.1 on 2022-08-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0026_alter_stand_stand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trener',
            name='trener_img',
            field=models.ImageField(default='media/default.png', upload_to='media/trener/%y/%m/%d/', verbose_name='Загрузить фото'),
        ),
    ]
