# Generated by Django 4.1 on 2022-08-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0028_alter_trener_trener_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_img',
            field=models.ImageField(blank=True, default='media/default.png', upload_to='media/club/%y/%m/%d/', verbose_name='Загрузить логотип'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='sportsman_img',
            field=models.ImageField(blank=True, default='media/default.png', upload_to='media/sportsman/%y/%m/%d/', verbose_name='Загрузить фото'),
        ),
    ]
