# Generated by Django 4.1 on 2022-09-04 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0029_alter_club_club_img_alter_sportsman_sportsman_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medal',
            name='medal_is_visible',
        ),
    ]
