# Generated by Django 4.1 on 2022-09-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0031_alter_stand_stand_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_name', models.CharField(max_length=50, verbose_name='Как к Вам обращаться:')),
                ('fb_email', models.EmailField(max_length=254, verbose_name='Email для связи:')),
                ('fb_message', models.TextField(blank=True, null=True, verbose_name='Ваше сообщение:')),
                ('fb_img', models.ImageField(upload_to='media/feedback/%y/%m/%d/', verbose_name='Загрузить фото')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
    ]
