# Generated by Django 4.1 on 2022-09-11 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0032_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'ОБРАТНАЯ СВЯЗЬ', 'verbose_name_plural': 'ОБРАТНАЯ СВЯЗЬ'},
        ),
    ]
