# Generated by Django 4.1 on 2022-09-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0033_alter_feedback_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='fb_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/feedback/%y/%m/%d/', verbose_name='Загрузить фото'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fb_message',
            field=models.TextField(verbose_name='Ваше сообщение:'),
        ),
    ]
