# Generated by Django 4.1 on 2022-09-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0038_alter_feedback_fb_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='fb_img',
            field=models.ImageField(blank=True, null=True, upload_to='media/feedback/%y/%m/%d/', verbose_name='Загрузить фото'),
        ),
    ]
