# Generated by Django 4.1 on 2022-09-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0039_alter_feedback_fb_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления'),
        ),
    ]
