# Generated by Django 4.1 on 2022-09-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0040_feedback_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsman',
            name='sportsman_country',
            field=models.CharField(max_length=30, verbose_name='Страна спортсмена'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='stand_description',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
    ]
