# Generated by Django 4.1 on 2022-09-24 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olimp', '0041_alter_sportsman_sportsman_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsSportsman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, verbose_name='Дата добавления')),
                ('text', models.TextField(verbose_name='Комментарии')),
                ('moderation_is_visible', models.BooleanField(blank=True, default=False, null=True, verbose_name='Скрытая запись')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olimp.sportsman', verbose_name='Новость')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии',
                'db_table': 'CommentsSportsman',
            },
        ),
    ]
