# Generated by Django 4.1 on 2022-09-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0042_commentssportsman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentssportsman',
            name='date_created',
            field=models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Дата добавления'),
        ),
    ]
