# Generated by Django 4.1 on 2022-09-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0043_alter_commentssportsman_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentssportsman',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления'),
        ),
    ]
