# Generated by Django 4.1 on 2022-09-25 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0044_alter_commentssportsman_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentssportsman',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='olimp.sportsman', verbose_name='Новость'),
        ),
    ]
