# Generated by Django 4.1 on 2022-09-25 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olimp', '0045_alter_commentssportsman_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentssportsman',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='date_event',
            field=models.DateField(verbose_name='Дата олимпиады'),
        ),
    ]
